### ISSUE TITLE
Home page on packagist is incorrect 

### ISSUE THREAD

**Issue by camfindlay** [BetterBrief/silverstripe-quickaddfield#1]
http://github.com/BetterBrief/silverstripe-quickaddnew is the current listed home page for this which is incorrect.

**Comment by willmorgan** [comment]
@dhensby [please fix](https://packagist.org/packages/betterbrief/silverstripe-quickaddfield) :heart:

**Comment by dhensby** [comment]
Fixed. thanks for spotting.
